### ISSUE TITLE
Automatic allocation

### ISSUE THREAD

**Issue by raduitache** [alk-language/java-semantics#6] opened 2020-05-22 08:32 UTC
In version 1.1, if I had a variable a and I would assign to a[2][3] something, everything up to that field would be allocated. Right now, no such thing is happening, I'm only being thrown an error

**Comment by llalexandru00** [comment] 2020-05-24 10:27
The issue is due to the recent changes on dynamic allocations. The bug was identified and it will be fixed in short time in the next release.

**Closed as completed** 2021-02-16 17:29 UTC
